options(repos = c(CRAN = "https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))
options(BioC_mirror = "https://mirrors.tuna.tsinghua.edu.cn/bioconductor")
options(Ncpus = parallel::detectCores())  
if (!requireNamespace("remotes", quietly=TRUE)) install.packages("remotes")
if (!requireNamespace("BiocManager", quietly=TRUE)) install.packages("BiocManager")

remotes::install_version("abind", version="1.4-8", upgrade="never")
remotes::install_version("assertthat", version="0.2.1", upgrade="never")
remotes::install_version("backports", version="1.5.0", upgrade="never")
remotes::install_version("base64enc", version="0.1-6", upgrade="never")
# Biobase 2.62.0 — conda: bioconductor-biobase=2.62.0 (已有)
# remotes::install_version("Biobase", version="2.62.0", upgrade="never")
# BiocGenerics 0.48.1 — conda: bioconductor-biocgenerics=0.48.1 (已有)
# remotes::install_version("BiocGenerics", version="0.48.1", upgrade="never")
remotes::install_version("BiocManager", version="1.30.27", upgrade="never")
# BiocVersion 3.18.1 — conda: bioconductor-data-packages (已有)
# remotes::install_version("BiocVersion", version="3.18.1", upgrade="never")
remotes::install_version("bitops", version="1.0-9", upgrade="never")
remotes::install_version("broom", version="1.0.12", upgrade="never")
# BSgenome.Hsapiens.UCSC.hg38 — Bioconductor 数据包，用 BiocManager 安装
# if (!requireNamespace("BSgenome.Hsapiens.UCSC.hg38", quietly=TRUE)) BiocManager::install("BSgenome.Hsapiens.UCSC.hg38", update=FALSE, ask=FALSE)
# BuenColors — GitHub 包（caleblareau/BuenColors），无 CRAN 版本
remotes::install_github("caleblareau/BuenColors", ref="v0.5.6", upgrade="never")
remotes::install_version("callr", version="3.7.6", upgrade="never")
remotes::install_version("cellranger", version="1.1.0", upgrade="never")
remotes::install_version("cli", version="3.6.5", upgrade="never")
remotes::install_version("codetools", version="0.2-20", upgrade="never")
remotes::install_version("coloc", version="5.2.3", upgrade="never")
remotes::install_version("colorspace", version="2.1-2", upgrade="never")
remotes::install_version("conflicted", version="1.2.0", upgrade="never")
remotes::install_version("cowplot", version="1.2.0", upgrade="never")
remotes::install_version("cpp11", version="0.5.3", upgrade="never")
remotes::install_version("crayon", version="1.5.3", upgrade="never")
# DelayedArray 0.28.0 — conda: bioconductor-delayedarray=0.28.0 (已有)
# remotes::install_version("DelayedArray", version="0.28.0", upgrade="never")
remotes::install_version("deldir", version="2.0-4", upgrade="never")
remotes::install_version("digest", version="0.6.39", upgrade="never")
remotes::install_version("dotCall64", version="1.2", upgrade="never")
remotes::install_version("dqrng", version="0.4.1", upgrade="never")
remotes::install_version("dtplyr", version="1.3.3", upgrade="never")
# EnsDb.Hsapiens.v86 — Bioconductor 数据包，用 BiocManager 安装
# if (!requireNamespace("EnsDb.Hsapiens.v86", quietly=TRUE)) BiocManager::install("EnsDb.Hsapiens.v86", update=FALSE, ask=FALSE)
remotes::install_version("fansi", version="1.0.7", upgrade="never")
remotes::install_version("farver", version="2.1.2", upgrade="never")
remotes::install_version("fastDummies", version="1.7.5", upgrade="never")
remotes::install_version("fastmatch", version="1.1-8", upgrade="never")
remotes::install_version("fitdistrplus", version="1.2-6", upgrade="never")
remotes::install_version("FNN", version="1.1.4.1", upgrade="never")
remotes::install_version("forcats", version="1.0.1", upgrade="never")
remotes::install_version("future", version="1.70.0", upgrade="never")
remotes::install_version("future.apply", version="1.20.2", upgrade="never")
remotes::install_version("gargle", version="1.6.1", upgrade="never")
# gchromVAR — GitHub 包（caleblareau/gchromVAR），无 CRAN 版本
remotes::install_github("caleblareau/gchromVAR", upgrade="never")
remotes::install_version("generics", version="0.1.4", upgrade="never")
# GenomeInfoDb 1.38.8 — conda: bioconductor-genomeinfodb=1.38.1 (已有)
# remotes::install_version("GenomeInfoDb", version="1.38.8", upgrade="never")
# GenomeInfoDbData 1.2.11 — conda: bioconductor-genomeinfodbdata=1.2.11 (已有)
# remotes::install_version("GenomeInfoDbData", version="1.2.11", upgrade="never")
# GenomicRanges 1.54.1 — conda: bioconductor-genomicranges=1.54.1 (已有)
# remotes::install_version("GenomicRanges", version="1.54.1", upgrade="never")
remotes::install_version("ggplot2", version="4.0.2", upgrade="never")
remotes::install_version("ggrepel", version="0.9.8", upgrade="never")
remotes::install_version("ggridges", version="0.5.7", upgrade="never")
remotes::install_version("globals", version="0.19.1", upgrade="never")
remotes::install_version("glue", version="1.8.0", upgrade="never")
remotes::install_version("goftest", version="1.2-3", upgrade="never")
remotes::install_version("googledrive", version="2.1.2", upgrade="never")
remotes::install_version("googlesheets4", version="1.1.2", upgrade="never")
remotes::install_version("gplots", version="3.3.0", upgrade="never")
remotes::install_version("gridExtra", version="2.3", upgrade="never")
remotes::install_version("gtable", version="0.3.6", upgrade="never")
remotes::install_version("haven", version="2.5.5", upgrade="never")
remotes::install_version("here", version="1.0.2", upgrade="never")
remotes::install_version("ica", version="1.0-3", upgrade="never")
remotes::install_version("ids", version="1.0.1", upgrade="never")
remotes::install_version("igraph", version="2.2.2", upgrade="never")
remotes::install_version("interp", version="1.1-6", upgrade="never")
# IRanges 2.36.0 — conda: bioconductor-iranges=2.36.0 (已有)
# remotes::install_version("IRanges", version="2.36.0", upgrade="never")
remotes::install_version("irlba", version="2.3.7", upgrade="never")
remotes::install_version("isoband", version="0.3.0", upgrade="never")
remotes::install_version("jpeg", version="0.1-11", upgrade="never")
remotes::install_version("jsonlite", version="2.0.0", upgrade="never")
remotes::install_version("KernSmooth", version="2.23-26", upgrade="never")
remotes::install_version("labeling", version="0.4.3", upgrade="never")
remotes::install_version("lattice", version="0.22-9", upgrade="never")
remotes::install_version("latticeExtra", version="0.6-31", upgrade="never")
remotes::install_version("lifecycle", version="1.0.5", upgrade="never")
remotes::install_version("listenv", version="0.10.1", upgrade="never")
remotes::install_version("lmtest", version="0.9-40", upgrade="never")
remotes::install_version("lubridate", version="1.9.5", upgrade="never")
remotes::install_version("magrittr", version="2.0.4", upgrade="never")
remotes::install_version("mapdata", version="2.3.1", upgrade="never")
remotes::install_version("maps", version="3.4.3", upgrade="never")
remotes::install_version("MASS", version="7.3-60", upgrade="never")
remotes::install_version("Matrix", version="1.6-5", upgrade="never")
# MatrixGenerics 1.14.0 — conda: bioconductor-matrixgenerics=1.14.0 (已有)
# remotes::install_version("MatrixGenerics", version="1.14.0", upgrade="never")
remotes::install_version("matrixStats", version="1.5.0", upgrade="never")
remotes::install_version("mgcv", version="1.9-0", upgrade="never")
remotes::install_version("mixsqp", version="0.3-54", upgrade="never")
remotes::install_version("modelr", version="0.1.11", upgrade="never")
remotes::install_version("munsell", version="0.5.1", upgrade="never")
remotes::install_version("nlme", version="3.1-168", upgrade="never")
remotes::install_version("otel", version="0.2.0", upgrade="never")
remotes::install_version("parallelly", version="1.46.1", upgrade="never")
remotes::install_version("patchwork", version="1.3.2", upgrade="never")
remotes::install_version("pbapply", version="1.7-4", upgrade="never")
remotes::install_version("pillar", version="1.11.1", upgrade="never")
remotes::install_version("pkgconfig", version="2.0.3", upgrade="never")
remotes::install_version("png", version="0.1-9", upgrade="never")
remotes::install_version("polyclip", version="1.10-7", upgrade="never")
remotes::install_version("processx", version="3.8.6", upgrade="never")
remotes::install_version("progressr", version="0.18.0", upgrade="never")
# ProtGenerics 1.34.0 — conda: bioconductor-protgenerics=1.34.0 (已有)
# remotes::install_version("ProtGenerics", version="1.34.0", upgrade="never")
remotes::install_version("ps", version="1.9.1", upgrade="never")
remotes::install_version("R6", version="2.6.1", upgrade="never")
remotes::install_version("ragg", version="1.2.6", upgrade="never")
remotes::install_version("RANN", version="2.6.2", upgrade="never")
remotes::install_version("raster", version="3.6-26", upgrade="never")
remotes::install_version("RColorBrewer", version="1.1-3", upgrade="never")
remotes::install_version("Rcpp", version="1.1.1", upgrade="never")
remotes::install_version("RcppAnnoy", version="0.0.23", upgrade="never")
remotes::install_version("RcppEigen", version="0.3.4.0.2", upgrade="never")
remotes::install_version("RcppHNSW", version="0.6.0", upgrade="never")
remotes::install_version("RcppProgress", version="0.4.2", upgrade="never")
remotes::install_version("RcppRoll", version="0.3.1", upgrade="never")
remotes::install_version("RcppTOML", version="0.2.3", upgrade="never")
remotes::install_version("RCurl", version="1.98-1.18", upgrade="never")
remotes::install_version("readxl", version="1.4.5", upgrade="never")
remotes::install_version("rematch", version="2.0.0", upgrade="never")
remotes::install_version("rematch2", version="2.1.2", upgrade="never")
remotes::install_version("remote", version="1.2.1", upgrade="never")
remotes::install_version("remotes", version="2.5.0", upgrade="never")
remotes::install_version("renv", version="1.2.2", upgrade="never")
remotes::install_version("reprex", version="2.1.1", upgrade="never")
remotes::install_version("reshape", version="0.8.10", upgrade="never")
remotes::install_version("reticulate", version="1.45.0", upgrade="never")
remotes::install_version("rlang", version="1.1.7", upgrade="never")
remotes::install_version("ROCR", version="1.0-12", upgrade="never")
remotes::install_version("rprojroot", version="2.1.1", upgrade="never")
remotes::install_version("RSpectra", version="0.16-2", upgrade="never")
remotes::install_version("rvest", version="1.0.5", upgrade="never")
# S4Arrays 1.2.1 — conda: bioconductor-s4arrays=1.2.0 (已有)
# remotes::install_version("S4Arrays", version="1.2.1", upgrade="never")
# S4Vectors 0.40.2 — conda: bioconductor-s4vectors=0.40.2 (已有)
# remotes::install_version("S4Vectors", version="0.40.2", upgrade="never")
remotes::install_version("S7", version="0.2.1", upgrade="never")
remotes::install_version("scales", version="1.4.0", upgrade="never")
remotes::install_version("scattermore", version="1.2", upgrade="never")
# SCAVENGE — GitHub 包（sankaranlab/SCAVENGE），无 CRAN 版本
remotes::install_github("sankaranlab/SCAVENGE", upgrade="never")
remotes::install_version("sctransform", version="0.4.3", upgrade="never")
remotes::install_version("selectr", version="0.5-1", upgrade="never")
# seqLogo 1.68.0 — conda: bioconductor-seqlogo=1.68.0 (已有)
# remotes::install_version("seqLogo", version="1.68.0", upgrade="never")
remotes::install_version("Seurat", version="5.4.0", upgrade="never")
# SeuratObject 5.3.0.9003 — 开发版，从 GitHub 安装
remotes::install_github("satijalab/seurat-object", upgrade="never")
remotes::install_version("Signac", version="1.16.0", upgrade="never")
remotes::install_version("sitmo", version="2.0.2", upgrade="never")
remotes::install_version("sp", version="2.2-1", upgrade="never")
remotes::install_version("spam", version="2.11-3", upgrade="never")
# SparseArray 1.2.4 — conda: bioconductor-sparsearray=1.2.2 (已有)
# remotes::install_version("SparseArray", version="1.2.4", upgrade="never")
remotes::install_version("spatstat.data", version="3.1-9", upgrade="never")
remotes::install_version("spatstat.explore", version="3.7-0", upgrade="never")
remotes::install_version("spatstat.geom", version="3.7-0", upgrade="never")
remotes::install_version("spatstat.random", version="3.4-4", upgrade="never")
remotes::install_version("spatstat.sparse", version="3.1-0", upgrade="never")
remotes::install_version("spatstat.univar", version="3.1-7", upgrade="never")
remotes::install_version("spatstat.utils", version="3.2-2", upgrade="never")
remotes::install_version("stringi", version="1.8.7", upgrade="never")
# SummarizedExperiment 1.32.0 — conda: bioconductor-summarizedexperiment=1.32.0 (已有)
# remotes::install_version("SummarizedExperiment", version="1.32.0", upgrade="never")
remotes::install_version("survival", version="3.8-6", upgrade="never")
remotes::install_version("susieR", version="0.14.2", upgrade="never")
remotes::install_version("systemfonts", version="1.3.2", upgrade="never")
remotes::install_version("tensor", version="1.5.1", upgrade="never")
remotes::install_version("terra", version="1.8-5", upgrade="never")
remotes::install_version("textshaping", version="1.0.5", upgrade="never")
remotes::install_version("tibble", version="3.3.1", upgrade="never")
remotes::install_version("tidyselect", version="1.2.1", upgrade="never")
remotes::install_version("tidyverse", version="2.0.0", upgrade="never")
remotes::install_version("timechange", version="0.4.0", upgrade="never")
remotes::install_version("utf8", version="1.2.6", upgrade="never")
remotes::install_version("uuid", version="1.2-2", upgrade="never")
remotes::install_version("uwot", version="0.2.4", upgrade="never")
remotes::install_version("vctrs", version="0.7.1", upgrade="never")
remotes::install_version("viridisLite", version="0.4.3", upgrade="never")
remotes::install_version("withr", version="3.0.2", upgrade="never")
# XVector 0.42.0 — conda: bioconductor-xvector=0.42.0 (已有)
# remotes::install_version("XVector", version="0.42.0", upgrade="never")
# zlibbioc 1.48.2 — conda: bioconductor-zlibbioc=1.48.0 (已有)
# remotes::install_version("zlibbioc", version="1.48.2", upgrade="never")
remotes::install_version("zoo", version="1.8-15", upgrade="never")

# ── 二次补装：对第一轮静默失败的包自动重试 ───────────────────────────────────
# remotes::install_* 失败时只打 warning 不中止，二次补装负责兜底
.retry <- function(pkg_name, install_expr) {
  if (!requireNamespace(pkg_name, quietly = TRUE)) {
    message(sprintf("[retry] %s missing, re-attempting...", pkg_name))
    tryCatch(
      eval(parse(text = install_expr)),
      error = function(e) message(sprintf("[retry] %s still failed: %s", pkg_name, e$message))
    )
  }
}

# CRAN 包
.retry("Seurat",
  'remotes::install_version("Seurat", version="5.4.0", upgrade="never",
   repos="https://mirrors.tuna.tsinghua.edu.cn/CRAN/")')
.retry("Signac",
  'remotes::install_version("Signac", version="1.16.0", upgrade="never",
   repos="https://mirrors.tuna.tsinghua.edu.cn/CRAN/")')

# GitHub 包（需要网络可达 GitHub 或已设置 GITHUB_PAT）
.retry("SeuratObject",
  'remotes::install_github("satijalab/seurat-object", upgrade="never")')
.retry("SCAVENGE",
  'remotes::install_github("sankaranlab/SCAVENGE", upgrade="never")')
.retry("BuenColors",
  'remotes::install_github("caleblareau/BuenColors", ref="v0.5.6", upgrade="never")')
.retry("gchromVAR",
  'remotes::install_github("caleblareau/gchromVAR", upgrade="never")')
